### ISSUE TITLE
Cannot open multibit HD Start up Error

### ISSUE THREAD

**Issue by fofoshique** [Multibit-Legacy/multibit-hd#974]
re-installed java - still have the same problem
![screen shot 2017-03-22 at 8 31 34 pm](https://cloud.githubusercontent.com/assets/3580327/24191109/d1ad88a8-0f3e-11e7-9b6a-394a9155d323.png)

**Comment by fofoshique** [comment]
anything?

**Comment by sakishinoda** [comment]
I also have the same issue, error message:

> java.lang.ClassCastException: org.slf4j.impl.SimpleLogger cannot be cast to ch.qos.logback.classic.Logger
	at org.multibit.hd.core.logging.LoggingFactory.getCleanRoot(LoggingFactory.java:119)
	at org.multibit.hd.core.logging.LoggingFactory.bootstrap(LoggingFactory.java:34)
	at org.multibit.hd.ui.MultiBitHD.start(MultiBitHD.java:118)
	at org.multibit.hd.ui.MultiBitHD.main(MultiBitHD.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:67)

**Comment by claudetymer** [comment]
@fofoshique
@sakishinoda
multibit bitcoin wallet has many bugs and issues, and I have solved most of its issues, I can recover your stuck transaction, and lost password for multibit bitcoin wallet file, before, I have recovered several multibit bitcoin wallets for my customers, you can find me at : walletsrecoveryservice@gmail.com

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/ @fofoshique @sakishinoda @hegjon @prusnak @drizzt
