### ISSUE TITLE
Cannot acces my MultiBit HD wallet

### ISSUE THREAD

**Issue by Imrooo** [Multibit-Legacy/multibit-hd#976]
Good evening,

at first, I wouldn't contact you if it wasn't the last thing I tried. I installed MultiBit a few days ago, written down the safe words, etc. Then, I moved my bitcoins to the new created wallet.

The day after, I couldn't access the wallet. The application required password, and I am certainly sure about the password, though all I got was "The password did not unlock the wallet". So I tried to restore it, written down the words, then the timestamp and nothing worked at all.

Attaching pictures of what I got.
Can you help me anyhow? 
Thank you.
![img_20170329_002408](https://cloud.githubusercontent.com/assets/26752689/24430673/111b0dac-1418-11e7-9cb6-bef3b7f1d3d3.jpg)
![img_20170329_002419](https://cloud.githubusercontent.com/assets/26752689/24430672/1117ec08-1418-11e7-8dc9-db954de4a584.jpg)

**Comment by ivan486** [comment]
i have same problem, alway show  "The password did not unlock the wallet" event i restore wallet and put new password, how can i do now :( money stuck there

**Comment by Imrooo** [comment]
I got help directly from MultiBit support in the end. Everything I had to do was downgrade MultiBit to 0.4.1 and restore the wallet once again. Everything is back to normal now.

**Comment by ivan486** [comment]
i was instal 0.4.1 but after restore got same problem, The password did not unlock the wallet" can you please give me how to contact them for help

**Comment by packtrack** [comment]
I have the exact same problem and I have been unable to solve it. 

I think it had to do with a transaction that for some reason would not confirm. I will continue to try and solve this.

**Comment by VTSTech** [comment]
Confirmed also in 0.5.1 x64 Windows

I get the following error on attempting to restore in the log.

Tried downgrading to 0.4.1. Didn't help.

{"@timestamp":"2017-06-08T16:13:56.981-04:00","@Version":1,"message":"Failed to restore wallet from seed phrase.","logger_name":"org.multibit.hd.ui.views.wizards.welcome.restore_wallet.RestoreWalletReportPanelView","thread_name":"safe-fixed-restore-wallet-0","level":"ERROR","level_value":40000,"stack_trace":"org.multibit.hd.core.exceptions.EncryptedFileReaderWriterException: Cannot read and decrypt the backup file 'K:\BACKUP\MultiBitHD\mbhd-b57649c3-bbbcead6-ca01449c-2bfff2b7-d43570ea-20170529010034.zip.aes'\r\n\tat org.multibit.hd.core.managers.BackupManager.loadZipBackup(BackupManager.java:463) ~[multibit-hd.jar:na]\r\n\tat org.multibit.hd.ui.views.wizards.welcome.restore_wallet.RestoreWalletReportPanelView.createWalletFromSeedPhrase(RestoreWalletReportPanelView.java:585) [multibit-hd.jar:na]\r\n\tat org.multibit.hd.ui.views.wizards.welcome.restore_wallet.RestoreWalletReportPanelView.handleCreateWalletStatus(RestoreWalletReportPanelView.java:411) [multibit-hd.jar:na]\r\n\tat org.multibit.hd.ui.views.wizards.welcome.restore_wallet.RestoreWalletReportPanelView.handleRestoreWallet(RestoreWalletReportPanelView.java:310) [multibit-hd.jar:na]\r\n\tat org.multibit.hd.ui.views.wizards.welcome.restore_wallet.RestoreWalletReportPanelView.access$000(RestoreWalletReportPanelView.java:62) [multibit-hd.jar:na]\r\n\tat org.multibit.hd.ui.views.wizards.welcome.restore_wallet.RestoreWalletReportPanelView$1.run(RestoreWalletReportPanelView.java:173) [multibit-hd.jar:na]\r\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_80]\r\n\tat java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_80]\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_80]\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_80]\r\n\tat java.lang.Thread.run(Unknown Source) [na:1.7.0_80]\r\nCaused by: org.multibit.hd.core.exceptions.EncryptedFileReaderWriterException: Cannot read and decrypt the backup file 'K:\BACKUP\MultiBitHD\mbhd-b57649c3-bbbcead6-ca01449c-2bfff2b7-d43570ea-20170529010034.zip.aes'\r\n\tat org.multibit.hd.core.managers.BackupManager.loadZipBackup(BackupManager.java:514) ~[multibit-hd.jar:na]\r\n\tat org.multibit.hd.core.managers.BackupManager.loadZipBackup(BackupManager.java:461) ~[multibit-hd.jar:na]\r\n\t... 10 common frames omitted\r\nCaused by: org.bitcoinj.crypto.KeyCrypterException: Could not decrypt: pad block corrupted\r\n\tat org.multibit.commons.crypto.AESUtils.decrypt(AESUtils.java:127) ~[multibit-hd.jar:na]\r\n\tat org.multibit.hd.core.managers.BackupManager.loadZipBackup(BackupManager.java:498) ~[multibit-hd.jar:na]\r\n\t... 11 common frames omitted\r\nCaused by: org.spongycastle.crypto.InvalidCipherTextException: pad block corrupted\r\n\tat org.spongycastle.crypto.paddings.PKCS7Padding.padCount(PKCS7Padding.java:63) ~[multibit-hd.jar:na]\r\n\tat org.spongycastle.crypto.paddings.PaddedBufferedBlockCipher.doFinal(PaddedBufferedBlockCipher.java:287) ~[multibit-hd.jar:na]\r\n\tat org.multibit.commons.crypto.AESUtils.decrypt(AESUtils.java:118) ~[multibit-hd.jar:na]\r\n\t... 12 common frames omitted\r\n"}

I was able to use https://github.com/HardCorePawn/multibit_recovery tool to recover the private keys.

The wallet did unlock/decrypt with the password in recovery tool. But not in either 0.4.1 or 0.5.1 of MultiBitHD Client.

I used the backup 0.5.1 mbhd.wallet.aes to recover. (I had since removed the file to install 0.4.1 and try again with 0.5.1 with no luck)

**Comment by ronensingerr** [comment]
Download Breadwallet on IOS and enter your wallet words. It saved my BTC.

**Comment by frederickmorty** [comment]
Whats going on 27 days and no update while our funds are locked?
One should be able to recover wallet with file + password, seed words is for lost password/wallet files.

https://github.com/HardCorePawn/multibit_recovery i was able to run but get error:
> Traceback (most recent call last):
  File "find_unspent_multibitHD_txes.py", line 256, in <module>
    wallet = load_wallet(wallet_file, get_password)
  File "find_unspent_multibitHD_txes.py", line 156, in load_wallet
    faddr = bitcoin.bin_to_b58check(bitcoin.deserialize_script(out.script_bytes)
[2])
  File "c:\python27\lib\site-packages\bitcoin\py2specials.py", line 43, in bin_t
o_b58check
    inp_fmtd = chr(int(magicbyte)) + inp
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by claudetymer** [comment]
@packtrack 
@Imrooo
@ivan486
multibit bitcoin wallet has many bugs and issues, and I have solved most of its issues, I can recover your stuck transaction, and lost password for multibit bitcoin wallet file, before, I have recovered several multibit bitcoin wallets for my customers, you can find me at : walletsrecoveryservice@gmail.com

**Comment by doge2021** [comment]
> I have the exact same problem and I have been unable to solve it.
> 
> I think it had to do with a transaction that for some reason would not confirm. I will continue to try and solve this.

there is bug in the old multibit wallet: https://btc2doge.com/multibit-hd-wallet-seed-words-not-work/

**Comment by doge2021** [comment]
> i was instal 0.4.1 but after restore got same problem, The password did not unlock the wallet" can you please give me how to contact them for help

there is bug in old multibit wallet: https://btc2doge.com/multibit-hd-wallet-seed-words-not-work/

**Comment by doge2021** [comment]
> I have the exact same problem and I have been unable to solve it.
> 
> I think it had to do with a transaction that for some reason would not confirm. I will continue to try and solve this.
@ronensingerr @ivan486 @Imrooo @packtrack 
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/
